version: 2.0

jobs:

  autofix-biweekly:
    docker:
      - image: gitpod/workspace-full
    steps:
      - run:
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
            git clone --recurse-submodules https://github.com/gitpod-io/workspace-images
            cd workspace-images
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
            git clone --recurse-submodules https://github.com/gitpod-io/gitpod
            cd gitpod
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
            git clone --recurse-submodules https://github.com/gitpod-io/definitely-gp
            cd definitely-gp
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
          no_output_timeout: 120m

  autofix-monthly:
    docker:
      - image: gitpod/workspace-full
    steps:
      - run:
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
            git clone --recurse-submodules https://github.com/gitpod-io/website
            cd website
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
            git clone --recurse-submodules https://github.com/jankeromnes/terraforming-mars-bot
            cd terraforming-mars-bot
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
          no_output_timeout: 120m

workflows:
  version: 2
  biweekly:
    triggers:
      - schedule:
          cron: "3 3 * * 0,3"
          filters:
            branches:
              only:
                - master
    jobs:
      - autofix-biweekly
  monthly:
    triggers:
      - schedule:
          cron: "3 3 9 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - autofix-monthly
